# Generated by Django 5.0 on 2026-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rol',
            field=models.CharField(choices=[('EST', 'Estudiant'), ('PRO', 'Professor')], default='EST', max_length=3),
        ),
    ]
