# Generated by Django 5.0 on 2026-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rol',
            field=models.CharField(choices=[('Estudiant', 'Estudiant'), ('Professor', 'Professor')], default='Estudiant', max_length=30),
        ),
    ]
